CREATE TABLE applications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title           TEXT        NOT NULL,
    company         TEXT,
    description     TEXT,
    link            TEXT        NOT NULL,
    location        TEXT,
    salary          TEXT,
    employment_type TEXT,
    source          TEXT,
    raw_payload     JSONB,
    current_status  VARCHAR(20) NOT NULL
        CHECK (current_status IN ('SAVED', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN')),
    captured_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX applications_user_id_current_status_idx ON applications (user_id, current_status);

CREATE TABLE application_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id   BIGINT      NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    event_date       DATE        NOT NULL,
    stage_category   VARCHAR(20) NOT NULL
        CHECK (stage_category IN ('SAVED', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN')),
    stage_label      TEXT,
    note             TEXT,
    rejection_reason VARCHAR(30)
        CHECK (rejection_reason IN ('SALARY_MISMATCH', 'POSITION_FILLED', 'LACK_OF_EXPERIENCE', 'NO_RESPONSE', 'OTHER')),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT rejection_reason_only_when_rejected
        CHECK (rejection_reason IS NULL OR stage_category = 'REJECTED')
);

CREATE INDEX application_events_application_id_idx ON application_events (application_id);
